# Generated by Django 5.0 on 2023-12-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_primary', models.CharField(max_length=250)),
                ('postal_code_primary', models.CharField(max_length=20)),
                ('city_primary', models.CharField(max_length=100)),
                ('phoneNumber1', models.CharField(blank=True, max_length=16, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=16, null=True)),
                ('address_secondery', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code_secondery', models.CharField(blank=True, max_length=20, null=True)),
                ('city_secondery', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(choices=[('aucun', 'aucun'), ('Mme', 'Mme.'), ('Mr.', 'Mr.')], default=1, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
