# Generated by Django 5.0 on 2023-12-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complement_adress_primary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='complement_adress_secondary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
